location        = ""
resource_group  = ""
storage_account = ""
virtual_network = ""
virtual_machine_frontend = ""
virtual_machine_backend = ""
virtual_machine_database = ""

azure_subscription_id = ""
azure_client_id = ""
azure_client_secret = ""
azure_tenant_id = ""

AWS_REGION = ""
AWS_ACCESS_KEY = ""
AWS_SECRET_ACCESS_KEY = ""
bucket_name = ""
vpc_name = ""
main_vpc_cidr = ""
public_subnets = ""
subnet_name = ""
igw_name = ""
rt_name = ""
ngw_ip_name = ""
ngw_name = ""
sg_name = ""